wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1642412976
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 3
      - 8
      - 16
      4: 3.8.8
      5: 0.12.9
      8:
      - 1
      - 3
      - 5
hyper:
  desc: null
  value: parameter
